export enum INewCompetitionStep {
  JOIN_OR_CREATE = "JOIN_OR_CREATE",
  TEAM_OR_INDIVIDUAL = "TEAM_OR_INDIVIDUAL",
  FIND_COMPETITION = "FIND_COMPETITION",
  NAME_AND_ICON = "NAME_AND_ICON",
  DATES = "DATES",
  REVIEW = "REVIEW",
}

export enum CompetitionStatus {
  FINISHED = "FINISHED",
  NOT_STARTED = "NOT_STARTED",
  NOT_SET = "NOT_SET",
  IN_PROGRESS = "IN_PROGRESS",
}
